export const products = [
  {
    id: 1,
    title: 'React',
    description: 'Une bibliothèque JavaScript pour créer des interfaces utilisateurs',
    url: 'https://reactjs.org',
    votes: 5,
    submittedAvatarUrl: 'images/avatars/bg.jpg',
    productImageUrl: 'images/products/code.jpg',
  },
  {
    id: 2,
    title: 'Angular',
    description: 'Un framework JavaScript moins bien que React',
    url: 'https://angular.io',
    votes: 89,
    submittedAvatarUrl: 'images/avatars/bg.jpg',
    productImageUrl: 'images/products/code.jpg',
  },
  {
    id: 3,
    title: 'PHP',
    description: 'Langage de ces morts',
    url: 'http://php.net',
    votes: 34,
    submittedAvatarUrl: 'images/avatars/bg.jpg',
    productImageUrl: 'images/products/code.jpg',
  },
  {
    id: 4,
    title: 'Vue',
    description: 'Une bibliothèque JavaScript',
    url: 'http://vuejs.org',
    votes: 23,
    submittedAvatarUrl: 'images/avatars/bg.jpg',
    productImageUrl: 'images/products/code.jpg',
  },
  {
    id: 5,
    title: 'Ruby',
    description: 'Un framework Web pour faire des prototypes rapides',
    url: 'https://ruby.org',
    votes: 41,
    submittedAvatarUrl: 'images/avatars/bg.jpg',
    productImageUrl: 'images/products/code.jpg',
  },
];